### ISSUE TITLE
Incorrect parameter notion ":userId" should be "{userId}" verified

### ISSUE THREAD

**Issue by Sciumo** [javalin/javalin-samples#21]
Incorrect parameter notion ":userId" should be "{userId}" verified
path = "/users/:userId", does not work.
path = "/users/{userId}", does work

https://github.com/javalin/javalin-samples/blob/d92d839593a28de51b908249202e4c047738f613/javalin6/javalin-openapi-example/src/main/java/io/javalin/example/java/user/UserController.java#L46C24-L46C25

**Comment by tipsy** [comment]
Thanks @Sciumo, fixed in https://github.com/javalin/javalin-samples/commit/84bc204ca60c7af79d109f36f16d8f27ab4aec9e
